version: '3'

services:
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: docker
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#    ports:
#      - "5432:5432"

  spring-app:
    image: marianascu/mini-app:latest
    container_name: app
    ports:
        - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://database-task7.cxiu9opm2qfq.us-east-1.rds.amazonaws.com:5432/docker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresroot
    depends_on:
      - postgres
